### ISSUE TITLE
Catalog of Strange Items

### ISSUE THREAD

**Issue by greg-kennedy** [NaNoGenMo/2018#7]
The goal here is to generate a glossy Catalog of bizarre and unique objects - like you might see in [SkyMall](https://en.wikipedia.org/wiki/SkyMall) or [The Sharper Image](https://en.wikipedia.org/wiki/The_Sharper_Image), except these will be even stranger.

The title, description and price of objects are procedurally generated.  (Now is as good a time as any to learn Tracery...)  Each object will also have a "photo", made by procedurally generating a [POV-Ray](https://www.povray.org/) scene file and rendering it.  The final collection of objects will go into a layout tool that generates a .pdf or .ps with cover, table of contents, back page, advertisements, etc.

For determining word count of the pictures, I'll probably go with counting the words in the POV-Ray script that drives rendering.

**Comment by LuRsT** [comment]
I really like the idea of the pictures representing the objects in the book, looking forward to this one!

**Comment by greg-kennedy** [comment]
From Slack on Nov. 26th:
> Feeling a bit discouraged this year.  I took a long vacation and I'm way behind, and I don't know if I will meet the deadline.

As predicted, I didn't make it :)

**Comment by greg-kennedy** [comment]
Since I was in the code for this year anyway, I spent a few minutes today cleaning up the code for a "final" commit - and also rendered a 20-page sample.

Code: https://github.com/greg-kennedy/CatalogOfStrangeItems
Sample: https://github.com/greg-kennedy/CatalogOfStrangeItems/blob/master/sample.pdf
