### ISSUE TITLE
UFO Poems

### ISSUE THREAD

**Issue by kevinhowbrook** [NaNoGenMo/2018#9]
I'm going to create a novel using UFO sightings data which in the form of a diary. 
The plan for this is to build a scraper to find UFO sighting data. :alien: 

### Sun 29 July 2018 - 15:13:29

I originally reported this incident to bufora with dogmatic response which i was never satisfied with. i felt that it lacked scrutiny. prognosis was a bolide space debris, however there was no explosion - the object simply disappeared, it was not a straight flight, it was utterly silent - the night was very still for a november, fireworks emit bangs, there were none. unusually it was very hard to range the object which i don't normally find difficult being a professional engineer. i also gave another incident to report from the same location of an orange orb in 2009 also reported with a dismissive response again that i felt didn't address the issue. photos attached carry the originally completed forms. please take seriously. many thanks.

**Comment by enkiv2** [comment]
I'd be surprised if nobody has yet scanned & transcribed all of Project
Blue Book. Since it's a government project, it *should* be in the public
domain.

**Comment by kevinhowbrook** [comment]
Ace resources, thanks!
I'm more looking at eye-witness accounts, not official reports. Simply because they are WAY funnier

**Comment by kevinhowbrook** [comment]
So.. changed my mind. I think I am going to make this a book of poems. So UFO sightings reports in the style of e.e cummings:

 --- 

Woke   
 to
 witness


 <strong>s   mall
</strong> <i>beings    </i> in <i>up  stairs
</i> in

 ou r house

 ---

**Comment by kevinhowbrook** [comment]
[Repo link](https://github.com/kevinhowbrook/ufo-poems)

**Comment by hugovk** [comment]
*Psst: it's not quite November :)*

**Comment by kevinhowbrook** [comment]
Sorry @hugovk I got way too carried away with this, am i disqualified?

**Comment by hugovk** [comment]
I think a little bit of prep is probably fine, people use libraries or tools they or others have made outside November, let's just try and keep in the spirit of things and do the main NOvel GENeration coding to NOvember. :)

**Comment by kevinhowbrook** [comment]
[Repo link](https://github.com/kevinhowbrook/ufo-poems)
[The text at the moment](https://github.com/kevinhowbrook/ufo-poems/blob/master/ufo_poems.md)

**Comment by hugovk** [comment]
Congratulations!

Here's an example poem:

>  <p>Saw the<br><br> <i>ob    ject</i> in <strong>the</strong> sky<br><br> tried<br> gettin g<br> <i>videos<br></i> nothing w   ould show co   uld only <strong>get<br><br><br></strong> one<br> picture whic   h<br><br> does  n't show    beaming<br><br> lights.<br> in  li    fe   <br><br> i   t was w   hit  e<br> but the picture shows<br> gre en. it<br> wasnt   the moon the moo   n was   <br> sout   h.</p>

**Comment by enkiv2** [comment]
I love this format!
